name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format Check
        run: deno fmt --check

      - name: '[Code] Lint'
        run: deno lint

      - name: '[Code] Test'
        run: deno test --coverage=coverage/

      - name: '[Docs] Lint'
        run: deno doc --lint

      - name: '[Docs] Test'
        run: deno test --doc

      # - name: Coverage
      #   run: deno coverage --lcov coverage/ > coverage.lcov

      # - name: Upload Coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     # token: ${{ secrets.CODECOV_TOKEN }} # Not required for public repos.
      #     files: ./coverage/coverage.lcov

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: CSpell
        uses: streetsidesoftware/cspell-action@v6
